spring:
  application:
    name: service-domain-challenge-core

  datasource:
    url: jdbc:postgresql://localhost:5432/booking_challenge
    username: booking_user
    password: booking_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

    properties:
      hibernate:
        format_sql: true

    show-sql: true